config/default/core.extension.yml
docroot/modules/custom/yukon_w3_migrate/src/Controller/ImportDataController.php
docroot/modules/custom/yukon_w3_migrate/yukon_w3_migrate.info.yml
docroot/modules/custom/yukon_w3_migrate/yukon_w3_migrate.permissions.yml
docroot/modules/custom/yukon_w3_migrate/yukon_w3_migrate.routing.yml

https://github.com/ytgov/yukon-ca/issues/142
**Steps:**
2. Login to Drupal admin
3. Click **Extend** on the top admin menu
4. In the **Filter** (Input Box), search **yukon w3 migrate**, check the checkbox and click **Install.**
5. After the custom module gets installed, click the link **[root-URL]/custom_migrate**. 
6. Wait for some time. When done, clear the Drupal cache using **drush cr** 
**Notes**
This is a custom module that will update the missing translations.
If the static function is not acceptable then we can try changing it. But it is used in Drupal core as well:
[Drupal Docs](https://www.drupal.org/docs/develop/development-tools/phpstan/handling-unsafe-usage-of-new-static#:~:text=If%20you%20choose%20not%20to%20make%20the%20class%20final%2C% …

Issue #142 - French translation does not appear

---

docroot/modules/custom/yukon_migrate/README.md
docroot/modules/custom/yukon_migrate/config/install/migrate_plus.migration_group.legacy_media.yml
docroot/modules/custom/yukon_migrate/migrations/yukon_migrate_files__public.yml

**Steps:**
1. Create a fresh Drupal 10 installation with minimal theme.  
2. Run the following command **./vendor/bin/drush config-get "system.site" uuid**. This step will display the new UUID that can be copied and replaced in the following file at line 4: **[web-root]/config/sync/system.site.yml**
3. Run **./vendor/bin/drush cim -y** to copy config files until you see the success message for completion.
4. Copy all the media files in **[web=root]/docroot/sites/default/files**. This folder content should be the same as Drupal 7 version of Yukon.ca
5. Run media migration first using this command in terminal **./vendor/bin/drush migrate:import yukon_migrate_files__public**. This should run for around 2 hours as per the current data size.  
6. Run **./vendor/bin/drush cr** to clear the …

Issue #332 - Split Data and Media Migrations

---

config/default/core.entity_view_display.node.topics_page.default.yml

[151](https://github.com/ytgov/yukon-ca/issues/151) .
**Steps:**

Issue #151 - Topic Page description heading visible in D10

---

config/default/language/fr/field.field.node.landing_page.field_primary_content.yml

https://github.com/ytgov/yukon-ca/issues/142
**Steps:**
2. Login to Drupal admin
3. Click **Extend** on the top admin menu
4. In the **Filter** (Input Box), search **yukon w3 migrate**, check the checkbox and click **Install.**
5. After the custom module gets installed, click the link **[root-URL]/custom_migrate**. 
6. Wait for some time. When done, clear the Drupal cache using **drush cr** 
**Notes**
This is a custom module that will update the missing translations.

Revise-Issue#142 - French translation does not appear 

---

docroot/modules/custom/yukon_migrate/migrations/paragraphs/yukon_migrate_quick_facts.yml
docroot/modules/custom/yukon_migrate/migrations/paragraphs/yukon_migrate_quick_facts_translations.yml
docroot/modules/custom/yukon_w3_migrate/src/Controller/ImportDataController.php

**Issue Addressed:**
https://github.com/ytgov/yukon-ca/issues/186
**Steps:**
2. Re-run migration update
3. Login to Drupal admin
4. Click Extend on the top admin menu
5. In the Filter (Input Box), search yukon w3 migrate, check the checkbox and click Install.
6. After the custom module gets installed, click the link [root-URL]/custom_migrate.
7. Wait for some time. When done, clear the Drupal cache using drush cr
**Notes**
This is a custom module that will update the missing translations.

Issue#186 - News should support multiple Quick facts

---

config/default/editor.editor.basic_html.yml
config/default/editor.editor.full_html.yml
config/default/editor.editor.wysiwyg_ckeditor.yml
config/default/filter.format.basic_html.yml
config/default/filter.format.full_html.yml
config/default/filter.format.wysiwyg_ckeditor.yml
config/default/language/fr/views.view.news_listing.yml
config/default/pathologic.settings.yml
config/default/user.role.author_in_page_alerts.yml
config/default/user.role.blog_author.yml
config/default/user.role.editor.yml
config/default/user.role.publisher.yml
config/default/user.role.site_administrator.yml
config/default/user.role.team_administrator.yml
config/default/user.role.translator.yml
config/default/user.role.writer.yml
config/default/views.view.blog_listing.yml
config/default/views.view.engagements.yml
config/default/views.view.event_listing.yml
config/default/views.view.news_listing.yml
config/default/views.view.workbench_current_user.yml
config/default/views.view.workbench_edited.yml
config/default/views.view.workbench_recent_content.yml
config/default/webform.webform.contact.yml
config/default/webform.webform.page_feedback.yml

Changes:
- Copy confirugation from 'WYSIWYG CKEDITOR' text-format into 'Full HTML' text-format
- Enable media support for 'Full HTML' text-editor
- disable 'WYSIWYG CKEDITOR' text-format
- Reorder CKEditor buttons for 'Full HTML' text-editor
- enable correct Linkit profile for 'Full HTML' text-editor
- disable 'Basic HTML' text-editor
- update affected views to stop using 'Basic HTML' text-editor

Mutlidev corrections: Task #64790: WYSIWYG Settings

---

README.md
migrate_initial.sh
migrate_update.sh

Adding two scripts, `migrate_initial.sh` and `migrate_update.sh` to normalize the data migration process.
This should close #484.

Scripts to standardize data migration process

---

config/default/node.type.basic_page.yml
config/default/node.type.in_page_alert.yml
config/default/node.type.site_wide_alert.yml
config/default/node.type.topics_page.yml

Enable 'preview' ability for content types
- Basic page
- In-Page Alert
- Site-Wide Alert
- Topics Page
In result - all content types have 'preview' ability.

Task #64789: Preview missing

---

docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_campground_directory_record.yml

Fixes #544
Note: This doesn't result in the site description field looking right. It's output as plain text (so you can see the HTML tags). That's a different issue.
This change migrates the correct data into the "Site description" field.

Migrate the correct "Site description" Campground field

---

composer.json
composer.lock
config/default/core.extension.yml
config/default/noreqnewpass.settings_form.yml
config/default/openid_connect.settings.facebook.yml
config/default/openid_connect.settings.generic.yml
config/default/openid_connect.settings.github.yml
config/default/openid_connect.settings.google.yml
config/default/openid_connect.settings.linkedin.yml
config/default/openid_connect.settings.okta.yml
config/default/openid_connect.settings.yml
docroot/modules/custom/yukon_sso/yukon_sso.info.yml
docroot/modules/custom/yukon_sso/yukon_sso.module
docroot/themes/custom/yukonca_glider/src/sass/pages/_index.scss
docroot/themes/custom/yukonca_glider/src/sass/pages/_login.page.scss

Since #653 won't happen before launch, this merge request bring SSO functionality to the `w3_staging_yukon` branch.
- Implements single-sign-on for YG staff
- Role assignment based on group membership
Relates to:
- #311
- #521 
- #312 
- #522
Reproduces
- #648 (which was to `master`)
1. Roll out the code
2. Composer install
3. Config import
4. Edit `settings.local.php`, if needed
```php
// SSO through MyYukon
$config['openid_connect.settings.generic']['settings'] = [
'client_id' => '1234',
'client_secret' => 'ABCD',
'authorization_endpoint' => 'https://sign-in.service.yukon.ca/authorize',
'token_endpoint' => 'https://sign-in.service.yukon.ca/oauth/token',
'userinfo_endpoint' => 'https://sign-in.service.yukon.ca/userinfo'
];
```

eServices - bring SSO to w3_staging_yukon

---

composer.json
composer.lock
config/default/views.view.content_overview.yml
config/default/views.view.feedback_results.yml

- New view: Content overview
- Updated view: Feedback results
At `admin/reports/yukon/content-count`, shows the count of different node types.
This addresses:
- #709
At `admin/dashboard/feedback`, shows as a table, grouped by page with filtering and pagination.
URL filter is missing.
The search version is currently in progress. Feedback on search pages is included in the regular report.
This addresses:
- #284
1. Roll out code
2. Install dependencies
3. Import config

eServices - admin views

---

config/default/core.date_format.month_date.yml

A minor configuration change that was made in prod is captured in code
Closes #754
None, as this change is already in prod.

eServices - prod config captured - leading zero on some dates

---

config/default/core.entity_form_display.node.directory_records_places.default.yml

Small config change to `core.entity_form_display.node.directory_records_places.default.yml`, removing references to `field_translation_status`, which hasn't landed yet. This problem landed as part of #866.
1. roll out code
2. import configuration `drush config:import`

eServices - hotfix for #866

---

config/default/field.field.node.basic_page.field_translation_status.yml
config/default/field.field.node.blog.field_translation_status.yml
config/default/field.field.node.campaign_page.field_translation_status.yml
config/default/field.field.node.campground_directory_record.field_translation_status.yml
config/default/field.field.node.department.field_translation_status.yml
config/default/field.field.node.directory_records_places.field_translation_status.yml
config/default/field.field.node.documents.field_translation_status.yml
config/default/field.field.node.engagement.field_translation_status.yml
config/default/field.field.node.event.field_translation_status.yml
config/default/field.field.node.homepage.field_translation_status.yml
config/default/field.field.node.in_page_alert.field_translation_status.yml
config/default/field.field.node.landing_page.field_translation_status.yml
config/default/field.field.node.landing_page_level_2.field_translation_status.yml
config/default/field.field.node.multi_step_page.field_translation_status.yml
config/default/field.field.node.news.field_translation_status.yml
config/default/field.field.node.site_wide_alert.field_translation_status.yml
config/default/field.field.node.topics_page.field_translation_status.yml
config/default/field.storage.node.field_translation_status.yml
docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.routing.yml

Two fixes for 
- https://github.com/ytgov/yukon-ca/issues/833
This merge request will address the following: 
Permission to access the admin/content_translation page
- https://github.com/ytgov/yukon-ca/issues/833#issuecomment-2725329170
Missing field (most recently identified in #866)
- https://github.com/ytgov/yukon-ca/pull/866#issuecomment-272534615
- partially undone in #874
`field_translation_status` is required for all content types and that is why we have a couple of config files.
1. Backup database
2. Roll out code
3. Import configuration `drush config:import`

W3-Mar-14-2025-v1

---

config/default/views.view.blog_type_info.yml
docroot/themes/custom/yukonca_glider/patterns/molecules/blog_type_info/pattern-blog-type-info.html.twig
docroot/themes/custom/yukonca_glider/templates/content/comment.html.twig

Updated blog template/view to remove yukon logo from the blog landing page.
This fixes Gitlab issue 195 (Blog: remove extra Yukon logo).
- git pull
- drush deploy -y
- theme build
- drush cr

Evolving Web - removed logo from blog main page (refs #68911)

---

docroot/themes/custom/yukonca_glider/src/sass/pages/_basic.page.scss

This PR is for part of this issue 
- https://github.com/ytgov/yukon-ca/issues/828. Specifically, about the [unwanted Title Case](https://github.com/ytgov/yukon-ca/issues/828#issuecomment-2695749081).
After merging this PR, run the following steps.
- Roll out code
- Rebuild the theme: `npm --prefix docroot/themes/custom/yukonca_glider i; npm --prefix docroot/themes/custom/yukonca_glider run build`
- Clear Drupal cache using `drush cr`

W3-Mar-18-2025-Issue-828

---

docroot/themes/custom/yukonca_glider/src/sass/pages/_campaign.page.scss
docroot/themes/custom/yukonca_glider/templates/content/node--campaign-page.html.twig

This PR is for Issue - https://github.com/ytgov/yukon-ca/issues/675.
As per last comment from @leeomara, following are the 4 pending things where points 1 and 3 seem to be fixed already. This PR will fix points 2 and 4.
1. Where link is blue instead of olive, I relinked the page and republished and that changed the colour [/en/sartyukon/3rd-party-reporting/en/sartyukon/3rd-party-reporting](https://yukon.ca/en/sartyukon/not-sure) - so resolved?
2. On this page, the page title is still gray instead of black https://yukon.ca/en/indigenous-artists-and-cultural-carriers-micro-grant
3. On this page, the text in the text block titled Contact is still incorrect (I put in another text block and pasted plain text, but no change)
4. Asterisk needs to be removed from feedback form
After merging this …

W3-Mar-17-2025-Issue-675

---

config/default/core.entity_view_display.paragraph.holiday_times.default.yml
docroot/themes/custom/yukonca_glider/src/sass/pages/_places.page.scss
docroot/themes/custom/yukonca_glider/templates/paragraphs/paragraph--holiday-times--default.html.twig

This PR is for Issue 
- #748.
If holiday hours = yes, timings will be displayed on the frontend.
After merging this PR, run the following steps.
- Drupal config import `drush cim`
- Rebuild the theme. `npm --prefix docroot/themes/custom/yukonca_glider i; npm --prefix docroot/themes/custom/yukonca_glider run build`
- Clear Drupal cache using `drush cr`.

W3-Mar-17-2025-Issue-748

---

config/default/goy_wildfire_low_bandwidth.settings.yml
docroot/modules/custom/goy_wildfire_low_bandwidth/goy_wildfire_low_bandwidth.module
docroot/sites/default/settings.php

Update the Wildland Fire Management low-bandwidth pages for the 2025 API changes that replaced the individual `*_RESPONSE` flags with the `RESPONSE_TYPE` status condition field.
None.
1. Pull code
2. Import configuration: `drush cim`
3. Clear caches: `drush cr`

eServices - Update WFM low-bandwidth pages for 2025 API changes - v1

---

config/default/block.block.yukonca_glider_views_block__facilities_listing_blocks_block_2.yml
config/default/core.entity_view_display.node.topics_page.default.yml
config/default/field.field.node.blog.field_comments.yml
config/default/language/fr/block.block.exposedformsearchpage_sidebar.yml
config/default/language/fr/views.view.search.yml

This merge request attempts to capture changes that were made to configuration in production since the last time we did this, https://github.com/ytgov/yukon-ca/pull/894.
- Fixes https://github.com/ytgov/yukon-ca/issues/827
- Default blog comment status to hidden
- On Topic pages, do not display "publisher"
- Disable the "Continuing care facilities" block (don't know about this)

eServices - Changes from prod 2025-05-04
