ytgov/yukon-ca

.github/workflows/drupal-deploy.yml
Workflow for Drupal deployment to pantheon
=> 43563 GitHub actions drupal deploy

composer.json, composer.lock, config/default/core.extension.yml
- refs #44489: Added the migrate_scanner module.
=> Migrate Basic Page content type.

composer.json, composer.lock, docroot/modules/custom/yukon_migrate/migrations/taxonomies/yukon_migrate_department.yml, docroot/modules/custom/yukon_migrate/migrations/taxonomies/yukon_migrate_teams.yml, docroot/modules/custom/yukon_migrate/src/Plugin/migrate/source/Term.php
Taxonomy migration for Teams and Department vocabularies
=> Ew 44282 teams taxonomy migration

docroot/modules/custom/yukon_migrate/migrations/media/yukon_migrate_images.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_basic_page.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_basic_page_translations.yml, docroot/modules/custom/yukon_migrate/migrations/paragraphs/yukon_migrate_charts.yml, docroot/modules/custom/yukon_migrate/migrations/paragraphs/yukon_migrate_collapsable_field.yml, docroot/modules/custom/yukon_migrate/migrations/yukon_migrate_files__public.yml
Created migrations for the:
- charts paragraph type; 
- collapsable field paragraph type;
- files;
- images media type;
- basic page content type with translations.
=> refs #44489: Basic page content type migration.

config/default/core.base_field_override.node.in_page_alert.promote.yml, config/default/core.base_field_override.node.in_page_alert.status.yml, config/default/core.entity_form_display.node.in_page_alert.default.yml, config/default/core.entity_view_display.node.in_page_alert.default.yml, config/default/core.entity_view_display.node.in_page_alert.teaser.yml, config/default/field.field.node.in_page_alert.body.yml, config/default/field.field.node.in_page_alert.field_department_term.yml, config/default/field.field.node.in_page_alert.field_field_assign_to.yml, config/default/field.field.node.in_page_alert.field_meta_tags.yml, config/default/field.field.node.in_page_alert.field_yukon_editorial_team.yml, config/default/field.storage.node.field_department_term.yml, config/default/field.storage.node.field_field_assign_to.yml, config/default/language.content_settings.node.in_page_alert.yml, config/default/node.type.in_page_alert.yml, config/default/workflows.workflow.content.yml
=> refs #44283: Created In-Page Alert CT.

composer.json, composer.lock, config/default/webform.settings.yml, docroot/themes/custom/yukonca_glider/src/sass/pages/_default.page.scss
- Disabled the CDN warning for the webform.
- Updated addtoany module.
- Added spacing to the page title.
=> refs #44677: Foundation bugfixes.

composer.json, composer.lock
Pull requests aren't building because the Pathologic D10 patch is no longer needed. The patch we were using against the dev branch was recently committed.
There are no known bugs or issues with code at this time.
1. Rollout code.
=> refs #001: Remove pathologic D10 patch that is committed.

config/default/views.view.in_page_alerts_admin_view.yml
Added In Page Alert admin view.
=> refs #45034: Added In Page Alert admin view.

config/default/views.view.in_page_alerts_admin_view.yml
=> refs #45034: Improved filter labels.

composer.json, composer.lock
Patch for conditional fields module has been committed (https://www.drupal.org/project/conditional_fields/issues/3286636). Removed patch from composer.json/lock.
=> refs #000: Remove conditional fields patch that has been committed.

config/default/field.field.paragraph.primary_content.field_popular_links.yml
Add primary_content fix for dependencies.
=> refs #001: Add primary_content and remove dependencies.

docroot/modules/custom/yukon_migrate/migrations/media/yukon_migrate_document.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_documents_page.yml, docroot/modules/custom/yukon_migrate/src/Plugin/migrate/source/YukonFile.php, docroot/modules/custom/yukon_migrate/yukon_migrate.module
=> EW refs #45271 Documents

.docksal/docksal.env, composer.json, composer.lock, config/default/core.extension.yml, config/default/webform.webform.page_feedback.yml, docroot/modules/custom/yukon_department/yukon_department.info.yml, docroot/modules/custom/yukon_department/yukon_department.module, patches/linkit-2712951-linkit-for-link.patch
- Updated linkit version to make patch apply. Fixed other patches to avoid references to MRs.
- Defined PHP version in Docksal and composer.json files.
- Added 'Page Feedback' webform.
=> #45291: Added 'Page Feedback' webform.

config/default/block.block.views_block__engagements_related_block.yml, config/default/block.block.views_engagements_other.yml, config/default/views.settings.yml, config/default/views.view.engagements.yml
Blocks: 
- views--exp-engagements-engagements 
- views-engagements-other 
- views-engagements-related_block
=> EW refs #45593: Engagements views

composer.json, composer.lock, docroot/modules/custom/yukon_migrate/migrations/media/yukon_migrate_audio.yml, docroot/modules/custom/yukon_migrate/src/Plugin/migrate/source/YukonFile.php
- Fixed the source plugin in the image media migration.
- Fixed the error in the yukon_migrate_file source plugin
- Added a patch to the drupal/core that improves migration commands performance.
=> refs #45618: Created the migration for the audio media type.

docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_home_page.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_home_page_translations.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_landing_page.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_landing_page_level_2.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_landing_page_level_2_translations.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_landing_page_translations.yml
This pull request adds path alias and path auto information for milestone 1 (homepage, landing page, landing page level 2).
There are no known bugs or issues with code at this time.
1. Deploy code.
2. Run migrations
=> refs #001: Kellett path migrations for milestone 1

config/default/block.block.breadcrumbs.yml, config/default/block.block.views_block__engagements_related_block.yml, config/default/block.block.views_block__in_page_alerts_block.yml, config/default/block.block.views_block__site_wide_alert_block.yml, config/default/block.block.views_documents_block.yml, config/default/block.block.yukonca_glider_local_actions.yml, config/default/block.block.yukonca_glider_local_tasks.yml, config/default/block.block.yukonca_glider_messages.yml, config/default/block.block.yukonca_glider_page_title.yml, config/default/core.entity_view_display.node.in_page_alert.default.yml
Adjusted block alert position and hide useful fields from full display mode.
=> refs #45034: Moved block to proper region and disabled unused fields for full display mode.

config/default/metatag.settings.yml
Switched on meta tags for needed content types.
=> EW refs# 45893: Metatags

docroot/modules/custom/yukon_migrate/migrations/media/yukon_migrate_audio.yml, docroot/modules/custom/yukon_migrate/migrations/media/yukon_migrate_audio_translations.yml, docroot/modules/custom/yukon_migrate/migrations/media/yukon_migrate_document_translations.yml, docroot/modules/custom/yukon_migrate/migrations/media/yukon_migrate_icon.yml, docroot/modules/custom/yukon_migrate/migrations/media/yukon_migrate_icon_translations.yml, docroot/modules/custom/yukon_migrate/migrations/media/yukon_migrate_images.yml, docroot/modules/custom/yukon_migrate/migrations/media/yukon_migrate_images_translations.yml, docroot/modules/custom/yukon_migrate/src/Plugin/migrate/source/YukonFile.php, docroot/modules/custom/yukon_migrate/src/Plugin/migrate/source/YukonFileTranslation.php, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
https://rm.ewdev.ca/issues/45281
- Added condition by the media field.
Created a source variable 'source_language' that use for choosing source language for file entity.
Created yukon_migrate_file_translation source plugin for creating translation migration.
- Created yukon_migrate_document_translations migration file for documents translations.
=> EW refs #45281: Media translation (only documents)

docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_news_translations.yml, docroot/modules/custom/yukon_migrate/migrations/paragraphs/yukon_migrate_quick_facts_translations.yml, docroot/modules/custom/yukon_migrate/migrations/paragraphs/yukon_migrate_quotes.yml, docroot/modules/custom/yukon_migrate/migrations/paragraphs/yukon_migrate_quotes_translations.yml
Issue with original field having all paragraphs set as und.
=> refs #004: Fix news paragraph migration translation bug.

config/default/views.view.news_listing.yml
https://github.com/ytgov/yukon-ca/issues/131
**Steps:**
1. Update the file.
=> Issue #131 - News items are repeated

config/default/views.view.news_listing.yml, docroot/modules/custom/yukon_migrate/migrations/paragraphs/yukon_migrate_image_gallery.yml
https://github.com/ytgov/yukon-ca/issues/129
**Steps:**
1. Update the file.
=> Issue #129 - Latest News" should be "Latest news"

config/default/block.block.views_block__latest_news_block_1.yml, config/default/paragraphs.paragraphs_type.image_gallery.yml
https://github.com/ytgov/yukon-ca/issues/133
**Steps:**
=> Issue #133 - Clarify language for managing Featured content

config/default/block.block.views_block__latest_news_block_1.yml
https://github.com/ytgov/yukon-ca/issues/130
**Steps:**
=> Issue #130 - Duplicate second "Latest news" section

config/default/language/fr/views.view.news_listing.yml
https://github.com/ytgov/yukon-ca/issues/125
**Steps:**
1. Add the new file
3. Clear drupal cache using **drush cr**.
=> Issue #125 - Latest News labels always in English

docroot/themes/custom/yukonca_glider/src/sass/layouts/_home.layout.scss
https://github.com/ytgov/yukon-ca/issues/128
**Steps:**
1. Update the theme stylesheet to fix this issue.
2. run the following commands to compile the CSS:
npm i
npm run clean
npm run build 
3. Clear Drupal cache using **drush cr** command
=> Issue #128 - Box icons and text larger

docroot/themes/custom/yukonca_glider/src/sass/base/_main.scss
https://github.com/ytgov/yukon-ca/issues/210
**Steps:**
1. Update the theme stylesheet to fix this issue.
2. run the following commands to compile the CSS:
npm i
npm run clean
npm run build 
3. Clear Drupal cache using "drush cr" command
=> Issue #210 - Missing horizontal bar

config/default/views.view.what_are_you_looking_for_landing_page_l2.yml
https://github.com/ytgov/yukon-ca/issues/140
**Steps:**
2. Run the drush cim -y command.
3. Clear Drupal cache using drush cr.
**Notes:**
This was not a migration problem but a problem with a view. We added filters to show distinct values and selected appropriate language to fix this issue.
=> Issue#140 - List of pages not consistent

README.md
https://github.com/ytgov/yukon-ca/issues/126
**Steps:**
Please see the **readme.md** file
=> Issue #126 - Homepage health and wellness section is empty

docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_landing_page_level_2.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_landing_page_level_2_translations.yml
https://github.com/ytgov/yukon-ca/issues/209
**Steps:**
Merge the PR
Run the migration rollback and re-import using the following steps:
./vendor/bin/drush migrate:rollback yukon_migrate_landing_page_level_2
./vendor/bin/drush migrate:rollback yukon_migrate_landing_page_level_2_translations
./vendor/bin/drush migrate:import yukon_migrate_landing_page_level_2
./vendor/bin/drush migrate:import yukon_migrate_landing_page_level_2_translations
=> Issue #209 - Missing Secondary Content

config/default/system.site.yml
[326](https://github.com/ytgov/yukon-ca/issues/326) .
**Steps:**
**Notes:**
1. We need to run this merge every time we do the full migration.
=> Issue #326 - Homepage is not setup as the default front page.

docroot/themes/custom/yukonca_glider/patterns/organisms/hero/pattern-hero--variant-image.html.twig, docroot/themes/custom/yukonca_glider/patterns/organisms/hero/scss/styles.scss
[138](https://github.com/ytgov/yukon-ca/issues/138) 
**Steps:**
=> Issue #138 - Text and icon in header overlap aurora graphic

config/default/block.block.yukonca_glider_page_title.yml, docroot/themes/custom/yukonca_glider/templates/layout/page.html.twig, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
[148](https://github.com/ytgov/yukon-ca/issues/148) .
**Steps:**
=> Issue #148 - Title bar styling is missing

config/default/core.entity_view_display.node.topics_page.default.yml
[150](https://github.com/ytgov/yukon-ca/issues/150) .
**Steps:**
=> Issue #150 - Metadescription is appearing in D10

config/default/node.type.basic_page.yml
[157](https://github.com/ytgov/yukon-ca/issues/157) .
**Steps:**
=> Issue #157 - Authorship and date should not be shown 

config/default/core.entity_form_display.node.basic_page.default.yml
PR combined for following two issues because the changes are in the same file:
[161](https://github.com/ytgov/yukon-ca/issues/161) 
[162](https://github.com/ytgov/yukon-ca/issues/162) 
**Steps:**
=> Issue # 161 - Reorder Basic page fields in admin | #162 - Sections/collapsable field/chart admin interface differs

config/default/core.entity_view_display.node.basic_page.default.yml
PR combined for following two issues because the changes are in the same file. Issue 340 was identified as a new issue.
[159](https://github.com/ytgov/yukon-ca/issues/159) 
[340](https://github.com/ytgov/yukon-ca/issues/340) 
**Steps:**
=> Issue #159 - Full width: off | #340 - Hide the text "On"

docroot/themes/custom/yukonca_glider/templates/layout/page.html.twig, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
[160](https://github.com/ytgov/yukon-ca/issues/160) .
**Steps:**
=> Issue #160 - Bottom aurora missing

config/default/block.block.editlanguageblock.yml, config/default/core.extension.yml, docroot/modules/custom/yukon_w3_custom/css/_variables.css, docroot/modules/custom/yukon_w3_custom/css/yukon_w3_custom.css, docroot/modules/custom/yukon_w3_custom/src/Plugin/Block/EditLanguageBlock.php, docroot/modules/custom/yukon_w3_custom/templates/edit-language.html.twig, docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.info.yml, docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.libraries.yml, docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.module
This PR addresses two issues - [145](https://github.com/ytgov/yukon-ca/issues/145) and [143](https://github.com/ytgov/yukon-ca/issues/143).
**Steps:**
**Notes:**
This is a custom module to add admin theme modifications.
=> Issue #145 - Button colours are different || #143 - English/French button missing 

config/default/core.entity_form_display.node.basic_page.default.yml
PR combined for following two issues because the changes are in the same file:
[161](https://github.com/ytgov/yukon-ca/issues/161) 
[162](https://github.com/ytgov/yukon-ca/issues/162) 
**Steps:**
=> ReviseIssue#162

config/default/block.block.editlanguageblock.yml
[143](https://github.com/ytgov/yukon-ca/issues/143).
**Steps:**
**Notes:**
This is a custom module to add admin theme modifications.
=> ReviseIssue#143 - - English/French button missing

config/default/language/fr/field.field.node.landing_page_level_2.field_primary_content.yml, config/default/language/fr/views.view.what_are_you_looking_for_landing_page_l2.yml, config/default/views.view.what_are_you_looking_for_landing_page_l2.yml
https://github.com/ytgov/yukon-ca/issues/142
**Steps:**
2. Login to Drupal admin
3. Click **Extend** on the top admin menu
4. In the **Filter** (Input Box), search **yukon w3 migrate**, check the checkbox and click **Install.**
5. After the custom module gets installed, click the link **[root-URL]/custom_migrate**. 
6. Wait for some time. When done, clear the Drupal cache using **drush cr** 
**Notes**
This is a custom module that will update the missing translations.
=> RevisedIssue#142 - French translation does not appear

config/default/block.block.mainnavigation.yml
[156](https://github.com/ytgov/yukon-ca/issues/156) 
**Steps:**
**Notes:**
Design part will be done separately
=> Issue#156 - Basic page missing main navigation (left) 

docroot/themes/custom/yukonca_glider/src/sass/layouts/_home.layout.scss, docroot/themes/custom/yukonca_glider/templates/layout/page.html.twig, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
https://github.com/ytgov/yukon-ca/issues/158
**Steps:**
1. Update the theme stylesheet to fix this issue.
2. run the following commands to compile the CSS:
npm i
npm run clean
npm run build 
3. Clear Drupal cache using "drush cr" command
=> Issue#158 - No header aurora 

config/default/core.entity_view_display.node.topics_page.default.yml
https://github.com/ytgov/yukon-ca/issues/152
https://github.com/ytgov/yukon-ca/issues/154
**Steps:**
2. Run the drush cim -y command.
3. Clear Drupal cache using drush cr.
=> Issue#152 - Yukon Editorial Team is viewable in D10 | Issue #154 - Department field appears in D10

config/default/views.view.what_are_you_looking_for_landing_page_l2.yml
https://github.com/ytgov/yukon-ca/issues/140
**Steps:**
2. Run the drush cim -y command.
3. Clear Drupal cache using drush cr.
=> RevisedIssue#140 - List of pages not consistent

config/default/core.entity_view_display.paragraph.image_gallery.default.yml, docroot/themes/custom/yukonca_glider/src/sass/base/_footer.scss, docroot/themes/custom/yukonca_glider/src/sass/base/_main.scss, docroot/themes/custom/yukonca_glider/templates/field/field--node--field-paragraphs--topics-page.html.twig, docroot/themes/custom/yukonca_glider/templates/field/field--node--field-whats-new-header--topics-page.html.twig, docroot/themes/custom/yukonca_glider/templates/field/field--paragraph--field-link--sub-heading.html.twig, docroot/themes/custom/yukonca_glider/templates/field/field--paragraph--field-title--image-gallery.html.twig, docroot/themes/custom/yukonca_glider/templates/layout/page.html.twig
[153](https://github.com/ytgov/yukon-ca/issues/153) 
**Steps:**
**Notes**
It will fix some other design issues beyond the 153 issue ID.
=> RevisedIssue#153 - [P-1] Page formatting of Headings and Items is not correct in D10

docroot/modules/custom/yukon_migrate/config/install/migrate_plus.migration_group.legacy_documents.yml, docroot/modules/custom/yukon_migrate/config/install/migrate_plus.migration_group.legacy_page_news.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_basic_page.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_basic_page_translations.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_documents_page.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_documents_page_translations.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_news.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_news_translations.yml
We have divided the migration into 9 groups. This will help us to run the complete migration easily on Pantheon.
=> Issue#332 - Split Data and Media Migrations

docroot/themes/custom/yukonca_glider/src/sass/base/_main.scss
[156](https://github.com/ytgov/yukon-ca/issues/156) 
**Steps:**
**Notes**
It will fix some other design issues beyond the 153 issue ID.
=> Issue#156 - Basic page missing main navigation (left)

config/default/paragraphs.paragraphs_type.image_gallery.yml
https://github.com/ytgov/yukon-ca/issues/133
**Steps:**
=> Fix Revert Issue #133. - Clarify language for managing Featured content 

config/default/core.entity_form_display.node.basic_page.default.yml
https://github.com/ytgov/yukon-ca/issues/162
**Steps:**
=> FixOrderContact Issue# 162 -  Sections/collapsable field/chart admin interface differs 

config/default/language.negotiation.yml
https://github.com/ytgov/yukon-ca/issues/415
**Steps:**
=> Issue#415 - Set default language URL

config/default/node.type.multi_step_page.yml
https://github.com/ytgov/yukon-ca/issues/165
**Steps:**
=> Issue #165 - Authorship and date should not be shown

config/default/filter.format.full_html.yml
https://github.com/ytgov/yukon-ca/issues/168
**Steps:**
=> Issue#168 - Email address not turned into a link

config/default/core.entity_form_display.node.multi_step_page.default.yml
https://github.com/ytgov/yukon-ca/issues/169
**Steps:**
=> Issue #169 - Reorder Multi-step fields in admin

config/default/views.view.news_listing.yml
https://github.com/ytgov/yukon-ca/issues/172
**Steps:**
=> Issue #172 - "Category" filter missing

config/default/views.view.news_listing.yml
https://github.com/ytgov/yukon-ca/issues/174
**Steps:**
=> Issue #174 - Filters function differently Apply button?

docroot/themes/custom/yukonca_glider/src/sass/base/_footer.scss, docroot/themes/custom/yukonca_glider/templates/field/field--node--field-related-link--news.html.twig
[182](https://github.com/ytgov/yukon-ca/issues/182) 
**Steps:**
=> Issue#182 - Related information heading missing colon (singular pages)

docroot/themes/custom/yukonca_glider/patterns/atoms/pagination/pattern-pagination.html.twig, docroot/themes/custom/yukonca_glider/tailwind.config.js
[177](https://github.com/ytgov/yukon-ca/issues/177) 
**Steps:**
=> Issue#177 - Pagination formatting is a bit different

docroot/themes/custom/yukonca_glider/src/sass/base/_main.scss, docroot/themes/custom/yukonca_glider/templates/field/field--node--field-news-release--news.html.twig
[183](https://github.com/ytgov/yukon-ca/issues/183) 
**Steps:**
=> Issue#183 -  News release number heading missing colon (singular pages)

config/default/field.field.node.multi_step_page.field_contact.yml, config/default/language/fr/field.field.node.multi_step_page.field_contact.yml
https://github.com/ytgov/yukon-ca/issues/167
**Steps:**
=> Issue-#167-stg  - English labels on French page

config/default/language/fr/views.view.news_listing.yml, config/default/views.view.news_listing.yml
https://github.com/ytgov/yukon-ca/issues/179
**Steps:**
=> Issue #179 - Missing translations for News filters

docroot/themes/custom/yukonca_glider/patterns/atoms/pagination/pattern-pagination.html.twig
[177](https://github.com/ytgov/yukon-ca/issues/177) 
**Steps:**
=> Issue# 177 -  Pagination formatting is a bit different

docroot/themes/custom/yukonca_glider/src/sass/base/_main.scss, docroot/themes/custom/yukonca_glider/templates/field/field--node--field-featured-image--news.html.twig
[184](https://github.com/ytgov/yukon-ca/issues/184) 
**Steps:**
=> Issue#184 - News images formatted wrong

docroot/themes/custom/yukonca_glider/templates/layout/page.html.twig, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
https://github.com/ytgov/yukon-ca/issues/180
**Steps:**
2. Clear Drupal cache using **drush cr**.
=> Issue#180 - Aurora graphic should not be on singular news pages

docroot/themes/custom/yukonca_glider/templates/content/node--news--full.html.twig
https://github.com/ytgov/yukon-ca/issues/181
**Steps:**
2. Clear Drupal cache using **drush cr**.
=> Issue#181 -  "Published" date format is different (singular pages)

config/default/field.field.node.news.field_contact.yml
https://github.com/ytgov/yukon-ca/issues/185
**Steps:**
=> Isseu#185 - Media contact formatting

config/default/language/fr/field.field.node.news.field_contact.yml, config/default/language/fr/field.field.node.news.field_news_release.yml, config/default/language/fr/field.field.node.news.field_quick_facts.yml, config/default/language/fr/field.field.node.news.field_related_link.yml
https://github.com/ytgov/yukon-ca/issues/188
**Steps:**
=> Issue#188 - French news shows English labels

docroot/modules/custom/yukon_w3_custom/css/highcharts.css, docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.libraries.yml
Issue Addressed:
https://github.com/ytgov/yukon-ca/issues/342
Steps:
Merge the PR
Run the following commands:
npm run build command inside [web-root]/docroot/themes/custom/yukonca_glider
terminus drush yukon-drupal-10.develop -- migrate:import --update yukon_migrate_basic_page
terminus drush yukon-drupal-10.develop -- migrate:import --update yukon_migrate_basic_page_translations
Clear Drupal cache using drush cr.
=> Issue#342 - Charts render as code not charts 

docroot/modules/custom/yukon_w3_custom/js/charts.js, docroot/themes/custom/yukonca_glider/src/js/theme.js
[342](https://github.com/ytgov/yukon-ca/issues/342) 
**Steps:**
2. Run the following commands:
**npm run build** command inside **[web-root]/docroot/themes/custom/yukonca_glider**
**terminus drush yukon-drupal-10.develop -- migrate:import --update yukon_migrate_basic_page**
**terminus drush yukon-drupal-10.develop -- migrate:import --update yukon_migrate_basic_page_translations**
=> Issue#342 - Charts render as code not charts

docroot/themes/custom/yukonca_glider/patterns/organisms/header/pattern-header.html.twig, docroot/themes/custom/yukonca_glider/patterns/organisms/header/scss/styles.scss, docroot/themes/custom/yukonca_glider/src/sass/base/_footer.scss, docroot/themes/custom/yukonca_glider/src/sass/base/_header.scss
=> Issue#459 - Header & Footer Layouts - Sitewide

README.md, config/translations/fr.customized.po, docroot/themes/custom/yukonca_glider/templates/layout/page--node--blog.html.twig, docroot/themes/custom/yukonca_glider/templates/layout/page.html.twig, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
External task for reference: http://app-cms-git01.gov.yk.ca/root/yukon-ca/-/issues/172
=> Task #64129: Date modified field at bottom of each page; format date/month/year [D10]

README.md
Update README to use `migrate_initial_and_update_w3.sh`
=> Update README to use new migration script

config/default/field.field.paragraph.text_and_image.field_display_section_title.yml, config/default/language/fr/views.view.content.yml, config/default/language/fr/views.view.media.yml, config/default/language/fr/views.view.media_library.yml, config/default/language/fr/views.view.scheduler_scheduled_content.yml, config/default/language/fr/views.view.scheduler_scheduled_media.yml, config/default/language/fr/views.view.scheduler_scheduled_taxonomy_term.yml, config/default/language/fr/views.view.workbench_edited.yml, config/default/language/fr/views.view.workbench_recent_content.yml, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_engagement.yml, docroot/modules/custom/yukon_migrate/src/Plugin/migrate/process/UriTransform.php, docroot/themes/custom/yukonca_glider/src/sass/base/_main.scss, docroot/themes/custom/yukonca_glider/src/sass/base/partials/_peak-times-graph.scss, docroot/themes/custom/yukonca_glider/src/sass/pages/_campaign.page.scss, docroot/themes/custom/yukonca_glider/src/sass/pages/_in_page_alert.page.scss, docroot/themes/custom/yukonca_glider/src/sass/pages/_landing.page.scss, docroot/themes/custom/yukonca_glider/templates/content/node--campaign-page.html.twig, docroot/themes/custom/yukonca_glider/templates/content/node--campground-directory-record--full.html.twig, docroot/themes/custom/yukonca_glider/templates/paragraphs/paragraph--text-and-image--default.html.twig, docroot/themes/custom/yukonca_glider/templates/paragraphs/paragraph--video-and-text.html.twig, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
- #181
- #188
- #201
- #202
- #203
- #205
- #207
- #218
- #287
- #567
- #600
=> W3- Oct-26-2024-v1

composer.json, config/default/editor.editor.full_html.yml, config/default/user.role.author_in_page_alerts.yml, config/default/user.role.author_site_wide_alerts.yml, config/default/user.role.editor.yml, config/default/user.role.publisher.yml, config/default/user.role.site_administrator.yml, config/default/user.role.translator.yml, config/default/user.role.writer.yml, config/default/views.view.feedback_results.yml, docroot/modules/custom/goy_wildfire_low_bandwidth/src/Form/GoyWildfireLowBandwidthForm.php, docroot/themes/custom/yukonca_glider/src/sass/pages/_campaign.page.scss, docroot/themes/custom/yukonca_glider/templates/content/node--campaign-page.html.twig, docroot/themes/custom/yukonca_glider/templates/layout/page--node--campaign-page.html.twig
This PR addresses the following issues:
- #208
- #284
- #372
- #644
=> W3 - Oct-31-2024-v1

docroot/themes/custom/yukonca_glider/templates/content/node--campground-directory-record--full.html.twig, docroot/themes/custom/yukonca_glider/templates/layout/page.html.twig, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
This PR will address the following issues:
- #264
- #265
- #668
=> W3- Nov-7-2024-v1

docroot/modules/custom/goy_yxy_flight_schedule/src/Plugin/Block/ArrivalsBlock.php, docroot/modules/custom/goy_yxy_flight_schedule/src/Plugin/Block/ArrivalsDeparturesBlock.php, docroot/modules/custom/yukon_w3_migrate/src/Controller/ImportDataController.php
=> W3 - Nov-10-2024-v1

composer.json, composer.lock, config/default/block.block.mainnavigation.yml, config/default/core.extension.yml, config/default/editor.editor.full_html.yml, config/default/imce.profile.admin.yml, config/default/imce.profile.member.yml, config/default/imce.settings.yml, config/default/language/fr/field.field.node.engagement.field_engagement_results.yml, config/default/language/fr/imce.profile.admin.yml, config/default/language/fr/imce.profile.member.yml, d10-queries.sql, docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_engagement_translation.yml, docroot/modules/custom/yukon_w3_migrate/src/Controller/ImportDataController.php, docroot/themes/custom/yukonca_glider/src/sass/base/_main.scss, docroot/themes/custom/yukonca_glider/src/sass/pages/_index.scss, docroot/themes/custom/yukonca_glider/src/sass/pages/_know-medications-impair-your-driving.scss, docroot/themes/custom/yukonca_glider/src/sass/pages/_multiple-step.page.scss, docroot/themes/custom/yukonca_glider/templates/content/node--campaign-page.html.twig, docroot/themes/custom/yukonca_glider/templates/paragraphs/paragraph--text--default.html.twig
This PR addresses the following issues:
- #370 
- #678 
- #695
- #701 
- #705
=> W3 - Nov-19-2024-v1

docroot/modules/custom/yukon_w3_migrate/src/Controller/ImportDataController.php, migrate_1_Dec_2024.sh, migrate_2_Dec_2024.sh
This PR will fix the following issues:
- #718 
- Transactional facilities missing migration
=> W3 - Dec-2-2024-v1

docroot/themes/custom/yukonca_glider/templates/layout/page--front.html.twig
This PR is to fix the missing "More on Yukon.ca" menu items on the homepage.
=> W3-Dec-3-2024-Fix-Menu-Homepage

composer.json, docroot/themes/custom/yukonca_glider/src/sass/base/_main.scss, docroot/themes/custom/yukonca_glider/src/sass/pages/_search.page.scss, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
=> Dec-8-2024

composer.lock
This PR is for:
- #769 
- #757 
This will also resolve the t function error that previously existed
=> W3-Dec-16-2024-v2

config/default/field.field.media.document.field_media_file.yml, config/default/field.field.node.campaign_page.field_paragraphs.yml
Changes from prod
This merge request attempts to capture changes that were made to configuration in production since the last time we did this, https://github.com/ytgov/yukon-ca/pull/771.
- #767
- #778 
=> eServices - Changes from prod 2024-12-18

docroot/themes/custom/yukonca_glider/patterns/organisms/footer/scss/styles.scss, docroot/themes/custom/yukonca_glider/templates/paragraphs/paragraph--contact-person--default.html.twig, docroot/themes/custom/yukonca_glider/templates/paragraphs/paragraph--holiday-times--default.html.twig, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
- #736 
- #753 
- #782 
- #789
=> W3-Dec-19-2024-V1

composer.lock, docroot/modules/custom/goy_yxy_flight_schedule/src/Plugin/Block/ArrivalsBlock.php, docroot/modules/custom/goy_yxy_flight_schedule/src/Plugin/Block/ArrivalsDeparturesBlock.php, docroot/themes/custom/yukonca_glider/patterns/organisms/footer/scss/styles.scss, docroot/themes/custom/yukonca_glider/templates/layout/node--documents.html.twig, docroot/themes/custom/yukonca_glider/templates/paragraphs/paragraph--contact-person--default.html.twig, docroot/themes/custom/yukonca_glider/templates/paragraphs/paragraph--holiday-times--default.html.twig, docroot/themes/custom/yukonca_glider/templates/table--464.html.twig, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
I think this is mainly this one merge request:
- #793
=> eServices - update main_w3_staging with recent main changes

docroot/modules/custom/yukon_w3_custom/js/yukon_w3_custom.js, docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.libraries.yml, docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.module, docroot/themes/custom/yukonca_glider/patterns/organisms/header/pattern-header.html.twig, docroot/themes/custom/yukonca_glider/src/sass/base/_base.scss, docroot/themes/custom/yukonca_glider/src/sass/base/_header.scss, docroot/themes/custom/yukonca_glider/src/sass/base/_main.scss, docroot/themes/custom/yukonca_glider/src/sass/pages/_basic.page.scss, docroot/themes/custom/yukonca_glider/tailwind.config.js, docroot/themes/custom/yukonca_glider/templates/content/node--news--full.html.twig, docroot/themes/custom/yukonca_glider/templates/layout/page--front.html.twig, docroot/themes/custom/yukonca_glider/templates/layout/page--node--campaign-page.html.twig, docroot/themes/custom/yukonca_glider/templates/paragraphs/paragraph--navigation-jump-point--default.html.twig, docroot/themes/custom/yukonca_glider/templates/paragraphs/paragraph--text--default.html.twig, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
This PR resolves the following issues:
- #747 
- #756
- #761
- #762
- #763
- #792 
- #795
- #796
- #797  
- #798
- #813 
- #814
=> W3-Dec-30-2024-v1

composer.json, composer.lock, config/default/core.base_field_override.node.directory_records_places.created.yml, config/default/core.base_field_override.node.directory_records_places.uid.yml, config/default/core.base_field_override.node.event.created.yml, config/default/core.base_field_override.node.event.uid.yml, docroot/modules/custom/yukon_w3_custom/src/Controller/ContentTranslationController.php, docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.module, docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.routing.yml, docroot/themes/custom/yukonca_glider/src/sass/pages/_campaign.page.scss, docroot/themes/custom/yukonca_glider/templates/layout/page--node--campaign-page.html.twig
=> W3-Jan-20-2025-v1

config/default/core.entity_form_display.node.campground_directory_record.default.yml, config/default/field.field.node.directory_records_places.field_community.yml, config/default/language/fr/views.view.search.yml, docroot/modules/custom/yukon_w3_custom/src/Controller/TeamDepartmentUpdate.php
This PR is for:
- #827 
- #831 
- #833
- #837
=> W3-Jan-23-2025-v1

docroot/modules/custom/yukon_w3_custom/src/Controller/ContentTranslationController.php, docroot/modules/custom/yukon_w3_custom/src/Form/SearchFilterForm.php, docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.routing.yml
Added admin permissions and dropdowns to sort missing translation content.
Issues:
- #817
- #817
=> W3-Jan-23-2025-v2

docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.module, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
This PR is for:
- #785 
- #795
=> W3-Jan-10-2025

docroot/modules/custom/yukon_w3_custom/src/Controller/TeamDepartmentUpdate.php
This PR is for the following issue:
- #718 
Please re-run this URL to update the editorial team:
/team_department_update
It will not impact the data already processed.
=> W3-Jan-5-2025-v1

config/default/field.field.node.directory_records_places.field_department_term.yml, docroot/themes/custom/yukonca_glider/templates/blocks/block--system-menu-block.html.twig, docroot/themes/custom/yukonca_glider/templates/navigation/breadcrumb.html.twig
This PR is for:
- #810 
- #845
=> W3-Feb-5-2025-v2

composer.json, composer.lock, docroot/themes/custom/yukonca_glider/templates/field/field--field-secondary-content.html.twig, patches/paragraghs-buttons_do_not_appear_if_translated_node-3125638-15.patch
Patch drupal/paragraphs to fix #804.
Dependencies changed:
```
PHP Production Dependencies (require)
+-----------------------------------+----------+-------------+-------------+
| Package                           | Action   | Old Version | New Version |
+-----------------------------------+----------+-------------+-------------+
| aws/aws-sdk-php                   | Upgraded |     3.334.7 |     3.336.7 |
| doctrine/common                   | Upgraded |       3.4.5 |       3.5.0 |
| doctrine/persistence              | Upgraded |       3.4.0 |       4.0.0 |
| drupal/ckeditor5_plugin_pack      | Upgraded |       1.2.3 |       1.2.4 |
| drupal/ckeditor5_premium_features | Upgraded |       1.3.4 |       1.3.5 |
| drupal/ds                         | Upgraded |      3.24.0 |      3.25.0 |
| …
```
=> eServices - hotfix for translated multi-step

config/default/block.block.yukonca_glider_peaktimesblock.yml, config/default/core.date_format.short.yml, config/default/core.date_format.short_format.yml, config/default/core.entity_form_display.paragraph.holiday_times.default.yml, config/default/views.view.feedback_results.yml, config/default/views.view.latest_news.yml
This merge request attempts to capture changes that were made to configuration in production since the last time we did this, https://github.com/ytgov/yukon-ca/pull/825.
- Change Short date formats to Year-month-day
- Add roles for access to Feedback view
- #851
- Update language of Campground Peak Times block
- #748
=> eServices - Changes from prod 2025-03-03

composer.json, composer.lock, docroot/modules/custom/yukon_w3_custom/css/yukon_w3_custom.css, docroot/modules/custom/yukon_w3_custom/js/yukon_w3_custom.js, docroot/modules/custom/yukon_w3_custom/src/Controller/AuthorAutocompleteController.php, docroot/modules/custom/yukon_w3_custom/src/Controller/ContentTranslationController.php, docroot/modules/custom/yukon_w3_custom/src/Controller/TeamDepartmentUpdate.php, docroot/modules/custom/yukon_w3_custom/src/Form/SearchFilterForm.php, docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.libraries.yml, docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.module, docroot/modules/custom/yukon_w3_custom/yukon_w3_custom.routing.yml, docroot/themes/custom/yukonca_glider/templates/blocks/block--system-menu-block.html.twig, docroot/themes/custom/yukonca_glider/templates/fontawesome/fontawesomeicon.html.twig, docroot/themes/custom/yukonca_glider/templates/layout/page--node--campaign-page.html.twig, docroot/themes/custom/yukonca_glider/templates/navigation/breadcrumb.html.twig, docroot/themes/custom/yukonca_glider/templates/views/views-view--search--page_1.html.twig, docroot/themes/custom/yukonca_glider/yukonca_glider.theme
Below are the **non-config** issues addressed by this PR:
- #693
- #718
- #731
- #755
- #764
- #795
- #796
- #808
- #817
- #833
- #841
- #842
- #845
This merge request includes updates to dependencies.
This merge request includes theme changes.
1. Backup the DB
2. Roll out the code
3. Composer install `composer install`
4. Rebuild the theme `npm --prefix docroot/themes/custom/yukonca_glider i; npm --prefix docroot/themes/custom/yukonca_glider run build`
5. Database update `drush updatedb`
6. Cache rebuild `drush cr`
=> W3-Mar-05-2025-Non-Config-Update

docroot/themes/custom/yukonca_glider/src/sass/base/_base.scss, docroot/themes/custom/yukonca_glider/src/sass/layouts/_home.layout.scss, docroot/themes/custom/yukonca_glider/src/sass/pages/_campaign.page.scss, docroot/themes/custom/yukonca_glider/src/sass/pages/_default.page.scss, docroot/themes/custom/yukonca_glider/src/sass/pages/_news_events.page.scss
This PR is for design related issues only:
- #675
- #725
- #812
- #826
After merging this PR, run the following steps.
1. Run the npm run build command inside [web-root]/docroot/themes/custom/yukonca_glider
2. Clear Drupal cache using drush cr.
This because of the complexity of having multiple issues in the same CSS files, we preferred to sent it as a single update.
=> W3-Mar-05-2025-CSS-Changes

config/default/field.field.node.documents.field_last_updated.yml, config/default/metatag.settings.yml
This merge request attempts to capture changes that were made to configuration in production since the last time we did this, https://github.com/ytgov/yukon-ca/pull/860.
- #871
- metatag trim end setting (don't know about this)
=> eServices - Changes from prod 2025-03-14

config/default/core.base_field_override.node.directory_records_places.created.yml, config/default/core.base_field_override.node.directory_records_places.uid.yml, config/default/core.entity_form_display.node.directory_records_places.default.yml, config/default/field.field.paragraph.text.field_section_content.yml, config/default/language/fr/block.block.views_block__places_listing_block_places_listing.yml, config/default/pathauto.settings.yml, config/default/workbench_email.workbench_email_template.draft_to_needs_review.yml, config/default/workbench_email.workbench_email_template.draft_to_ready_to_publish.yml
These are the 5 config related issues:
- #727
- #756
- #768 
- #777 
- #781
These changes are config only.
1. Backup DB
2. Roll out code changes
3. Import configuration drush `config:import`
=> W3-Mar-07-2025-v2

config/default/user.role.editor.yml
This merge request attempts to capture changes that were made to configuration in production since the last time we did this, https://github.com/ytgov/yukon-ca/pull/873.
- https://github.com/ytgov/yukon-ca/issues/885
=> eServices - Changes from prod 2025-03-26

docroot/themes/custom/yukonca_glider/yukonca_glider.theme
This PR is for Issue - #785.
It will show time with double zero's and will also fix additional issue which was previous done for something else.  Please review the file changes and let us know if modifications are required.  
1. Roll out code
2. Rebuilt cache
=> W3-Mar-17-2025-Issue-785

docroot/themes/custom/yukonca_glider/templates/paragraphs/paragraph--text-and-image--default.html.twig
- #832 
2. Clear cache  `drush cr`
=> W3-Mar-18-2025-Issue-832

docroot/themes/custom/yukonca_glider/patterns/organisms/hero/pattern-hero--variant-image.html.twig
This PR will fix - #830
Steps:
Merge the PR 
Clear cache >> drush cr
=> W3-Mar-18-2025-Issue-830

docroot/themes/custom/yukonca_glider/src/sass/pages/_multiple-step.page.scss
This PR is for Issue 
- https://github.com/ytgov/yukon-ca/issues/798.
After merging this PR, run the following steps.
1. Roll out the code
2. Run the npm run build command `npm --prefix docroot/themes/custom/yukonca_glider i; npm --prefix docroot/themes/custom/yukonca_glider run build`
3. Clear Drupal cache using `drush cr`
=> W3-Mar-18-2025-Issue-798

config/default/field.field.node.directory_records_places.field_open_24_hours.yml, config/default/language/fr/field.field.node.directory_records_places.field_open_24_hours.yml
Changes from prod
This merge request attempts to capture changes that were made to configuration in production since the last time we did this, https://github.com/ytgov/yukon-ca/pull/888.
-  https://github.com/ytgov/yukon-ca/issues/891
=> eServices - Changes from prod 2025-04-09

config/default/field.field.node.blog.field_comments.yml
- #867
2. Config import `drush config:import`
3. Clear cache  `drush cr`
=> W3-Apr-10-2025-Issue-867

docroot/themes/custom/yukonca_glider/templates/content/node--event.html.twig
- #876
2. Clear cache  `drush cr`
=> W3-Apr-10-2025-Issue-876

docroot/themes/custom/yukonca_glider/templates/content/node--event.html.twig
- #901 
2. Clear cache  `drush cr`
=> W3-Apr-21-2025-Issue-901

composer.json, docroot/.htaccess
- #900
2. ~~Run composer install~~ the patch is redundant, so long as `.htaccess` exists and is updated.
3. ~~Clear cache  `drush cr`~~
=> W3-Apr-21-2025-Issue-900

docroot/themes/custom/yukonca_glider/patterns/organisms/tabs/pattern-tabs--variant-pills.html.twig
- #899
2. Clear cache  `drush cr`
=> W3-Apr-25-2025-Issue-899

config/default/language/fr/field.field.node.news.field_backgrounder.yml
This merge request attempts to capture changes that were made to configuration in production since the last time we did this, https://github.com/ytgov/yukon-ca/pull/918.
- Fixes #919
=> eServices - Changes from prod 2025-05-28
